### ISSUE TITLE
add multi-level nested lists support

### ISSUE THREAD

**Issue by chaseadamsio** [chaseadamsio/goorgeous#3]

**Comment by kaushalmodi** [comment]
To add to this, here is a MWE to test this support:

- And unordered list begins with `+` or `-`.
- Two empty lines ends a list.

Here is the [spec](http://orgmode.org/manual/Plain-lists.html#Plain-lists).

```
** Unordered Lists
Begin a list with a =+= or =-= sign. Items belonging to the same list must have the same indentation on the first line. To add sub-lists, increase indentation of that list item's =+= or =-= sign as shown in the below example.

Two consecutive blank lines after a list ends the list. Below, the list with =baz1/= and =baz2/= will be in a separate =<ul>= wrapper in HTML.
#+BEGIN_SRC text
- /baz1
- /baz2


+ /foo1
+ /foo2
+ /foo3
  - bar1
  - bar2
#+END_SRC
- /baz1
- /baz2


+ /foo1
+ /foo2
+ /foo3
  - bar1
  - bar2
```

Above snippet is from my large org syntax examples file (so you see the section numbers below). This is what org exports to html:
![image](https://cloud.githubusercontent.com/assets/3578197/23030868/105192c4-f43d-11e6-8a92-1e5e1689accc.png)

**Comment by humanfactors** [comment]
Has there been any update on this - it would be incredibly useful.

**Comment by kaushalmodi** [comment]
@humanfactors 

Wow, it's been a year since this :)

I then ventured into developing the [`ox-hugo`][1] package, an Org exporter that exports to Hugo front-matter + Markdown (and HTML where needed). I live and breathe in Emacs + Org environment, so getting all of the Org syntax work was very important to port my existing Org documents, which can be [very complicated][2], to Hugo rendered [pages][3].

[1]: https://github.com/kaushalmodi/ox-hugo
[2]: https://gitlab.com/kaushalmodi/kaushalmodi.gitlab.io/blob/master/content-org/notes/string-fns-nim-vs-python.org
[3]: https://scripter.co/notes/string-functions-nim-vs-python/

**Comment by jrmiller82** [comment]
I'd love an update too. This is pretty important functionality for an org parser.

**Comment by chaseadamsio** [comment]
Sorry I kinda went dark. I'm almost done with the refactor for goorgeous to handle how many ever deeply nested lists you may have. Here's a snapshot [generated from a deeply nested list](https://github.com/chaseadamsio/goorgeous/blob/feat-lexAndParse/transform/snapshots/unordered-list/with-2-deep-nested-children-list.org.html).

**Comment by chaseadamsio** [comment]
I had a branch I was getting ready to PR into Hugo, but it looks like @niklasfasching PR'ed a new org parser, so I'm closing all the issues here, deprecating and archiving goorgeous.
