### ISSUE TITLE
Not parsing nested lists correctly

### ISSUE THREAD

**Issue by jrmiller82** [chaseadamsio/goorgeous#75]
See issue in downstream:

https://github.com/go-gitea/gitea/issues/3122

```
- bullet 1
  - sub bullet
```

Should render something like:

```
<ul>
  <li>bullet 1</li>
  <ul>
    <li>sub bullet</li>
  </ul>
</ul>
```

**Comment by NateScarlet** [comment]
Should be duplicated with #3

**Comment by chaseadamsio** [comment]
Sorry for the late reply, but this will be fixed in the release I'm currently working on. Here's a preview of the snapshot [generated for deeply nested lists](https://github.com/chaseadamsio/goorgeous/blob/feat-lexAndParse/transform/snapshots/unordered-list/with-2-deep-nested-children-list.org.html).

**Comment by chaseadamsio** [comment]
I had a branch I was getting ready to PR into Hugo this week that fixed this, but it looks like @niklasfasching PR'ed a new org parser, so I'm closing all the issues here, deprecating and archiving goorgeous.
